# Generated by Django 5.0.3 on 2024-05-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={},
        ),
        migrations.AddField(
            model_name='conversation',
            name='has_new_messages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
