# Generated by Django 5.0.3 on 2024-04-07 08:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('main', '0006_alter_listingspaceoverview_bedroom_furnished_and_more'),
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conversatio',
            new_name='Conversation',
        ),
    ]
