# Generated by Django 4.2.6 on 2024-05-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
