# Generated by Django 5.0.3 on 2024-04-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_alter_conversationmessage_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationmessage',
            name='created_by',
        ),
    ]
