# Generated by Django 4.2.6 on 2024-04-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
    ]
