# Generated by Django 4.2.6 on 2024-05-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymnet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id_document',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tenant_photo',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default='timezone.now'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
