# Generated by Django 5.0.3 on 2024-05-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymnet', '0003_booking_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
