# Generated by Django 4.2.6 on 2024-05-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='income_proof',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='profession_proof',
        ),
    ]
