# Generated by Django 5.0.2 on 2024-03-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listing_available_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_end',
            field=models.DateTimeField(null=True),
        ),
    ]
