# Generated by Django 4.2.6 on 2024-04-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listing_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
