# Generated by Django 4.2.6 on 2024-05-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_upload_id_proof_remove_upload_income_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='id_proof',
            field=models.FileField(default='', upload_to='uploads/Id/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='income_proof',
            field=models.FileField(default='', upload_to='uploads/Income/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='profession_proof',
            field=models.FileField(default='', upload_to='uploads/Profession/'),
            preserve_default=False,
        ),
    ]
