# Generated by Django 5.0.2 on 2024-03-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listing_address_listing_latitude_listing_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='title',
        ),
        migrations.AddField(
            model_name='listing',
            name='house_kind',
            field=models.CharField(choices=[('private_room', 'Private Room'), ('shared_room', 'Shared Room')], default='', max_length=200, verbose_name='House Kind'),
            preserve_default=False,
        ),
    ]
