# Generated by Django 5.0.2 on 2024-04-09 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        ('main', '0003_image_seller_listinghouseamenities_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='conversation.contact'),
            preserve_default=False,
        ),
    ]
