# Generated by Django 4.2.6 on 2024-02-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rentalconditions_rulesandpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesandpreferences',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='Gender'),
        ),
    ]
