# Generated by Django 5.0.3 on 2024-04-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingspaceoverview',
            name='bedroom_furnished',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=24),
        ),
        migrations.AlterField(
            model_name='listingspaceoverview',
            name='bedroom_size',
            field=models.CharField(max_length=24, verbose_name='Bedroom Size'),
        ),
    ]
