# Generated by Django 4.2.6 on 2024-05-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_upload_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='', max_length=200, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
