# Generated by Django 4.2.6 on 2024-02-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_rulesandpreferences_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalconditions',
            name='advanced_price',
        ),
        migrations.RemoveField(
            model_name='rentalconditions',
            name='basic_price',
        ),
        migrations.RemoveField(
            model_name='rentalconditions',
            name='daily_contract',
        ),
        migrations.RemoveField(
            model_name='rentalconditions',
            name='flexible_cancellation',
        ),
        migrations.RemoveField(
            model_name='rentalconditions',
            name='fortnight_contract',
        ),
        migrations.RemoveField(
            model_name='rentalconditions',
            name='monthly_contract',
        ),
        migrations.RemoveField(
            model_name='rentalconditions',
            name='strict_cancellation',
        ),
        migrations.RemoveField(
            model_name='rulesandpreferences',
            name='any_tenant',
        ),
        migrations.RemoveField(
            model_name='rulesandpreferences',
            name='professional_tenant',
        ),
        migrations.RemoveField(
            model_name='rulesandpreferences',
            name='proof_identity',
        ),
        migrations.RemoveField(
            model_name='rulesandpreferences',
            name='proof_income',
        ),
        migrations.RemoveField(
            model_name='rulesandpreferences',
            name='proof_occupation',
        ),
        migrations.RemoveField(
            model_name='rulesandpreferences',
            name='student_tenant',
        ),
        migrations.AddField(
            model_name='rentalconditions',
            name='cancellation',
            field=models.CharField(choices=[('strict cancellation', 'Strict Cancellation'), ('flexible cancellation', 'Flexible Cancellation')], default='', max_length=24, verbose_name='Cancellation Option'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalconditions',
            name='contract',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('fortnight', 'Fortnight')], default=1, max_length=24, verbose_name='Contract Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalconditions',
            name='price',
            field=models.CharField(choices=[('basic price', 'Basic Price'), ('advanced price', 'Advanced Price')], default=1, max_length=24, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rulesandpreferences',
            name='proof',
            field=models.CharField(choices=[('proof of identity', 'Proof of Identity'), ('proof of income', 'Proof of Income'), ('proof of occupation', 'Proof of Occupation')], default=1, max_length=24, verbose_name='Proof for Tenant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rulesandpreferences',
            name='tenant',
            field=models.CharField(choices=[('any ', 'Any'), ('student ', 'Student'), ('working professional', 'Working Professional')], default=1, max_length=24, verbose_name='Tenant Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listinghouseamenities',
            name='bed',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=24, verbose_name='Bed'),
        ),
        migrations.AlterField(
            model_name='listinghouseamenities',
            name='desk',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=24, verbose_name='Desk'),
        ),
        migrations.AlterField(
            model_name='listinghouseamenities',
            name='living_room_furnished',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=24, verbose_name='Living Room Furnished'),
        ),
        migrations.AlterField(
            model_name='listinghouseamenities',
            name='wifi',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=24, verbose_name='Wifi'),
        ),
        migrations.AlterField(
            model_name='listinghousearea',
            name='bathroom',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=24, verbose_name='Bathroom'),
        ),
        migrations.AlterField(
            model_name='listinghousearea',
            name='garden',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=24, verbose_name='Garden'),
        ),
        migrations.AlterField(
            model_name='listinghousearea',
            name='kitchen',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=24, verbose_name='Kitchen'),
        ),
        migrations.AlterField(
            model_name='listinghousearea',
            name='living_room',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=24, verbose_name='Living Room'),
        ),
        migrations.AlterField(
            model_name='listinghousearea',
            name='toilet',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=24, verbose_name='Toilet'),
        ),
        migrations.AlterField(
            model_name='listingspaceoverview',
            name='bedroom_size',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=24, verbose_name='Bedroom Size'),
        ),
        migrations.AlterField(
            model_name='rulesandpreferences',
            name='maximum_age',
            field=models.CharField(choices=[('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55'), ('above 60', 'Above 60')], default=None, max_length=24),
        ),
        migrations.AlterField(
            model_name='rulesandpreferences',
            name='minimum_age',
            field=models.CharField(choices=[('under 15', 'Under 15'), ('18', '18'), ('20', '20')], default=None, max_length=24),
        ),
    ]
