# Generated by Django 4.2.6 on 2024-05-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_listing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='house_kind',
            field=models.CharField(choices=[('Private room', 'Private Room'), ('Shared room', 'Shared Room')], max_length=200, verbose_name='House Kind'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=200),
        ),
    ]
