# Generated by Django 5.0.2 on 2024-02-28 11:25

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_rentalconditions_advanced_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to=main.utils.user_listing_path),
        ),
    ]
