# Generated by Django 4.2.6 on 2024-04-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_addressoflisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressoflisting',
            name='Address',
            field=models.CharField(max_length=100),
        ),
    ]
