# Generated by Django 5.0.2 on 2024-02-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_listamenities_listarea_listrentalconditions_and_more'),
        ('main', '0007_alter_listing_image'),
    ]

    operations = [
    ]
