# Generated by Django 4.2.6 on 2024-04-29 16:59

from django.db import migrations, models
import django.db.models.deletion
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_is_email_verified_and_more'),
        ('main', '0007_alter_addressoflisting_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_photo', models.ImageField(upload_to=main.utils.user_listing_path)),
                ('house_map', models.ImageField(upload_to=main.utils.user_listing_path)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
