# Generated by Django 4.2.6 on 2024-05-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_listing_house_kind_alter_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='accepted',
            field=models.BooleanField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='upload',
            name='document',
            field=models.ImageField(upload_to='uploads/documents/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='id_proof',
            field=models.ImageField(upload_to='uploads/Id/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='income_proof',
            field=models.ImageField(upload_to='uploads/Income/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='profession_proof',
            field=models.ImageField(upload_to='uploads/Profession/'),
        ),
    ]
