# Generated by Django 4.2.6 on 2024-05-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalconditions',
            name='contract',
            field=models.CharField(choices=[('shelter', 'Shelter'), ('business', 'Business')], max_length=24, verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='rulesandpreferences',
            name='proof',
            field=models.CharField(max_length=24, verbose_name='Proof for Tenant'),
        ),
    ]
