# Generated by Django 5.0.3 on 2024-04-07 11:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_listing_created_by'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedlisting',
            name='like_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='likedlisting',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='main.listing'),
        ),
        migrations.AlterField(
            model_name='likedlisting',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_listings', to='users.profile'),
        ),
    ]
