# Generated by Django 5.0.3 on 2024-04-07 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_likedlisting_like_date_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedlisting',
            name='like_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='likedlisting',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.listing'),
        ),
        migrations.AlterField(
            model_name='likedlisting',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
