# Generated by Django 4.2.6 on 2024-05-11 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_upload_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='house_map',
            field=models.ImageField(upload_to='uploads/house_map/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id_photo',
            field=models.ImageField(upload_to='uploads/gov_id/'),
        ),
    ]
