# Generated by Django 4.2.6 on 2024-05-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_document_created_at_alter_document_house_map_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='maximum_rental_period',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='minimum_rental_period',
        ),
        migrations.AddField(
            model_name='listing',
            name='house_map',
            field=models.ImageField(default='', upload_to='uploads/house_map/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='id_photo',
            field=models.ImageField(default='', upload_to='uploads/gov_id/'),
            preserve_default=False,
        ),
    ]
