# Generated by Django 4.2.6 on 2024-05-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_upload_document_remove_upload_move_out_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='available_end',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='move_in_date',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
