# Generated by Django 4.2.6 on 2024-05-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_conversation_message_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
