# Generated by Django 4.2.6 on 2024-02-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingSpaceOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_size', models.CharField(max_length=24)),
                ('house_mate_no', models.CharField(max_length=24)),
                ('bedroom_size', models.CharField(max_length=24)),
                ('bedroom_furnished', models.CharField(max_length=24)),
            ],
        ),
    ]
