# Generated by Django 4.2.6 on 2024-02-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listingspaceoverview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingHouseAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.CharField(max_length=24)),
                ('wifi', models.CharField(max_length=24)),
                ('desk', models.CharField(max_length=24)),
                ('living_room_furnished', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='ListingHouseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen', models.CharField(max_length=24)),
                ('toilet', models.CharField(max_length=24)),
                ('bathroom', models.CharField(max_length=24)),
                ('living_room', models.CharField(max_length=24)),
                ('garden', models.CharField(max_length=24)),
            ],
        ),
    ]
