# Generated by Django 5.0.2 on 2024-02-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20240228_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListAmenities',
        ),
        migrations.DeleteModel(
            name='ListArea',
        ),
        migrations.DeleteModel(
            name='ListRentalConditions',
        ),
        migrations.DeleteModel(
            name='ListRulesPreferences',
        ),
        migrations.DeleteModel(
            name='ListSpaceOverview',
        ),
    ]
