# Generated by Django 5.0.2 on 2024-03-05 19:11

import django.db.models.deletion
import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_likedlisting'),
        ('users', '0002_remove_location_state_remove_location_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to=main.utils.user_listing_path)),
                ('image2', models.ImageField(upload_to=main.utils.user_listing_path)),
                ('image3', models.ImageField(upload_to=main.utils.user_listing_path)),
                ('image4', models.ImageField(upload_to=main.utils.user_listing_path)),
                ('image5', models.ImageField(upload_to=main.utils.user_listing_path)),
                ('alt_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='seller',
            new_name='host',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='color',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='model',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='vin',
        ),
        migrations.AddField(
            model_name='listing',
            name='available_end',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='available_start',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='main.listing')),
                ('amenity_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='amenity_type', to='main.listinghouseamenities')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=models.ManyToManyField(through='main.Amenity', to='main.listinghouseamenities'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.listing')),
            ],
        ),
        migrations.CreateModel(
            name='HouseArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Listing_house_area', to='main.listing')),
                ('house_area', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='house_area', to='main.listinghousearea')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_house_area',
            field=models.ManyToManyField(through='main.HouseArea', to='main.listinghousearea'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photos',
            field=models.ManyToManyField(to='main.image'),
        ),
        migrations.CreateModel(
            name='ListingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_spaces', to='main.listing')),
                ('space_overview', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='space_overview', to='main.listingspaceoverview')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_space_overview',
            field=models.ManyToManyField(through='main.ListingSpace', to='main.listingspaceoverview'),
        ),
        migrations.CreateModel(
            name='RentalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_conditions', to='main.listing')),
                ('rental_conditions', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rental_conditions', to='main.rentalconditions')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='rental_condtion',
            field=models.ManyToManyField(through='main.RentalCondition', to='main.rentalconditions'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.listing')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='rooms',
            field=models.ManyToManyField(to='main.room'),
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adults', models.PositiveSmallIntegerField()),
                ('children', models.PositiveSmallIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='rooms',
            field=models.ManyToManyField(through='main.RoomBooking', to='main.room'),
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Listing_rules', to='main.listing')),
                ('rules_and', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rules_and_preferences', to='main.rulesandpreferences')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='rules_and_preferences',
            field=models.ManyToManyField(through='main.Rules', to='main.rulesandpreferences'),
        ),
    ]
