# Generated by Django 5.0.2 on 2024-03-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_image_room_rename_seller_listing_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='likedlisting',
            name='like_date',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='available_end',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='available_start',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='updated_at',
        ),
    ]
