# Generated by Django 5.0.2 on 2024-03-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_booking_check_in_date_booking_check_out_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='available_end',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='available_start',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
