# Generated by Django 5.0.2 on 2024-03-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='likedlisting',
            name='like_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='available_end',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='available_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
