# Generated by Django 5.0.2 on 2024-03-06 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_booking_check_out_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_out_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
